# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/rouille/Documents/rendezvous/src/app/gui/odaslive.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_OdasLive(object):
    def setupUi(self, OdasLive):
        OdasLive.setObjectName("OdasLive")
        self.gridLayout = QtWidgets.QGridLayout(OdasLive)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.source1 = QtWidgets.QFrame(OdasLive)
        self.source1.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.source1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.source1.setObjectName("source1")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.source1)
        self.verticalLayout_10.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_6 = QtWidgets.QLabel(self.source1)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_4.addWidget(self.label_6)
        self.line = QtWidgets.QFrame(self.source1)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_4.addWidget(self.line)
        self.label_7 = QtWidgets.QLabel(self.source1)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_4.addWidget(self.label_7)
        self.source1AzimuthValueLabel = QtWidgets.QLabel(self.source1)
        self.source1AzimuthValueLabel.setIndent(4)
        self.source1AzimuthValueLabel.setObjectName("source1AzimuthValueLabel")
        self.verticalLayout_4.addWidget(self.source1AzimuthValueLabel)
        self.label_9 = QtWidgets.QLabel(self.source1)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_4.addWidget(self.label_9)
        self.source1ElevationValueLabel = QtWidgets.QLabel(self.source1)
        self.source1ElevationValueLabel.setIndent(4)
        self.source1ElevationValueLabel.setObjectName("source1ElevationValueLabel")
        self.verticalLayout_4.addWidget(self.source1ElevationValueLabel)
        self.verticalLayout_10.addLayout(self.verticalLayout_4)
        self.horizontalLayout_2.addWidget(self.source1)
        self.source2 = QtWidgets.QFrame(OdasLive)
        self.source2.setAutoFillBackground(False)
        self.source2.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.source2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.source2.setObjectName("source2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.source2)
        self.verticalLayout_3.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.source2)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.line_2 = QtWidgets.QFrame(self.source2)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_2.addWidget(self.line_2)
        self.label_3 = QtWidgets.QLabel(self.source2)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.source2AzimuthValueLabel = QtWidgets.QLabel(self.source2)
        self.source2AzimuthValueLabel.setIndent(4)
        self.source2AzimuthValueLabel.setObjectName("source2AzimuthValueLabel")
        self.verticalLayout_2.addWidget(self.source2AzimuthValueLabel)
        self.label_5 = QtWidgets.QLabel(self.source2)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.source2ElevationValueLabel = QtWidgets.QLabel(self.source2)
        self.source2ElevationValueLabel.setIndent(4)
        self.source2ElevationValueLabel.setObjectName("source2ElevationValueLabel")
        self.verticalLayout_2.addWidget(self.source2ElevationValueLabel)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.horizontalLayout_2.addWidget(self.source2)
        self.source3 = QtWidgets.QFrame(OdasLive)
        self.source3.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.source3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.source3.setObjectName("source3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.source3)
        self.verticalLayout_6.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_8 = QtWidgets.QLabel(self.source3)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_5.addWidget(self.label_8)
        self.line_3 = QtWidgets.QFrame(self.source3)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_5.addWidget(self.line_3)
        self.label_10 = QtWidgets.QLabel(self.source3)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_5.addWidget(self.label_10)
        self.source3AzimuthValueLabel = QtWidgets.QLabel(self.source3)
        self.source3AzimuthValueLabel.setIndent(4)
        self.source3AzimuthValueLabel.setObjectName("source3AzimuthValueLabel")
        self.verticalLayout_5.addWidget(self.source3AzimuthValueLabel)
        self.label_11 = QtWidgets.QLabel(self.source3)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_5.addWidget(self.label_11)
        self.source3ElevationValueLabel = QtWidgets.QLabel(self.source3)
        self.source3ElevationValueLabel.setIndent(4)
        self.source3ElevationValueLabel.setObjectName("source3ElevationValueLabel")
        self.verticalLayout_5.addWidget(self.source3ElevationValueLabel)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.horizontalLayout_2.addWidget(self.source3)
        self.source4 = QtWidgets.QFrame(OdasLive)
        self.source4.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.source4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.source4.setObjectName("source4")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.source4)
        self.verticalLayout_8.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_12 = QtWidgets.QLabel(self.source4)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_7.addWidget(self.label_12)
        self.line_4 = QtWidgets.QFrame(self.source4)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_7.addWidget(self.line_4)
        self.label_13 = QtWidgets.QLabel(self.source4)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_7.addWidget(self.label_13)
        self.source4AzimuthValueLabel = QtWidgets.QLabel(self.source4)
        self.source4AzimuthValueLabel.setIndent(4)
        self.source4AzimuthValueLabel.setObjectName("source4AzimuthValueLabel")
        self.verticalLayout_7.addWidget(self.source4AzimuthValueLabel)
        self.label_14 = QtWidgets.QLabel(self.source4)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_7.addWidget(self.label_14)
        self.source4ElevationValueLabel = QtWidgets.QLabel(self.source4)
        self.source4ElevationValueLabel.setIndent(4)
        self.source4ElevationValueLabel.setObjectName("source4ElevationValueLabel")
        self.verticalLayout_7.addWidget(self.source4ElevationValueLabel)
        self.verticalLayout_8.addLayout(self.verticalLayout_7)
        self.horizontalLayout_2.addWidget(self.source4)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.btnStartOdas = QtWidgets.QPushButton(OdasLive)
        self.btnStartOdas.setObjectName("btnStartOdas")
        self.horizontalLayout.addWidget(self.btnStartOdas)
        self.btnStopOdas = QtWidgets.QPushButton(OdasLive)
        self.btnStopOdas.setObjectName("btnStopOdas")
        self.horizontalLayout.addWidget(self.btnStopOdas)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(OdasLive)
        QtCore.QMetaObject.connectSlotsByName(OdasLive)

    def retranslateUi(self, OdasLive):
        _translate = QtCore.QCoreApplication.translate
        self.label_6.setText(_translate("OdasLive", "Source 1"))
        self.label_7.setText(_translate("OdasLive", "Azimuth:"))
        self.source1AzimuthValueLabel.setText(_translate("OdasLive", "0.00000"))
        self.label_9.setText(_translate("OdasLive", "Elevation:"))
        self.source1ElevationValueLabel.setText(_translate("OdasLive", "0.00000"))
        self.label_2.setText(_translate("OdasLive", "Source 2"))
        self.label_3.setText(_translate("OdasLive", "Azimuth:"))
        self.source2AzimuthValueLabel.setText(_translate("OdasLive", "0.00000"))
        self.label_5.setText(_translate("OdasLive", "Elevation:"))
        self.source2ElevationValueLabel.setText(_translate("OdasLive", "0.00000"))
        self.label_8.setText(_translate("OdasLive", "Source 3"))
        self.label_10.setText(_translate("OdasLive", "Azimuth:"))
        self.source3AzimuthValueLabel.setText(_translate("OdasLive", "0.00000"))
        self.label_11.setText(_translate("OdasLive", "Elevation:"))
        self.source3ElevationValueLabel.setText(_translate("OdasLive", "0.00000"))
        self.label_12.setText(_translate("OdasLive", "Source 4"))
        self.label_13.setText(_translate("OdasLive", "Azimuth:"))
        self.source4AzimuthValueLabel.setText(_translate("OdasLive", "0.00000"))
        self.label_14.setText(_translate("OdasLive", "Elevation:"))
        self.source4ElevationValueLabel.setText(_translate("OdasLive", "0.00000"))
        self.btnStartOdas.setText(_translate("OdasLive", "Start ODAS"))
        self.btnStopOdas.setText(_translate("OdasLive", "Stop ODAS"))

