# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/rouille/Documents/rendezvous/src/app/gui/speech_to_text.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SpeechToText(object):
    def setupUi(self, SpeechToText):
        SpeechToText.setObjectName("SpeechToText")
        SpeechToText.resize(626, 541)
        self.gridLayout = QtWidgets.QGridLayout(SpeechToText)
        self.gridLayout.setObjectName("gridLayout")
        self.btnTranscribe = QtWidgets.QPushButton(SpeechToText)
        self.btnTranscribe.setObjectName("btnTranscribe")
        self.gridLayout.addWidget(self.btnTranscribe, 4, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 4, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(SpeechToText)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.language = QtWidgets.QComboBox(self.groupBox_2)
        self.language.setObjectName("language")
        self.gridLayout_3.addWidget(self.language, 1, 1, 1, 1)
        self.encoding = QtWidgets.QComboBox(self.groupBox_2)
        self.encoding.setObjectName("encoding")
        self.gridLayout_3.addWidget(self.encoding, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 3, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMinimumSize(QtCore.QSize(161, 0))
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 0, 0, 1, 1)
        self.sampleRate = QtWidgets.QSpinBox(self.groupBox_2)
        self.sampleRate.setObjectName("sampleRate")
        self.gridLayout_3.addWidget(self.sampleRate, 3, 1, 1, 1)
        self.model = QtWidgets.QComboBox(self.groupBox_2)
        self.model.setObjectName("model")
        self.gridLayout_3.addWidget(self.model, 2, 1, 1, 1)
        self.enhanced = QtWidgets.QCheckBox(self.groupBox_2)
        self.enhanced.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.enhanced.setText("")
        self.enhanced.setObjectName("enhanced")
        self.gridLayout_3.addWidget(self.enhanced, 6, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_7.setWordWrap(False)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 6, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 2, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_2, 1, 0, 1, 2)
        self.groupBox_3 = QtWidgets.QGroupBox(SpeechToText)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.transcriptionResult = QtWidgets.QTextBrowser(self.groupBox_3)
        self.transcriptionResult.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.transcriptionResult.setObjectName("transcriptionResult")
        self.verticalLayout.addWidget(self.transcriptionResult)
        self.gridLayout.addWidget(self.groupBox_3, 2, 0, 1, 2)
        self.groupBox = QtWidgets.QGroupBox(SpeechToText)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.audioDataPath = QtWidgets.QLineEdit(self.groupBox)
        self.audioDataPath.setObjectName("audioDataPath")
        self.gridLayout_2.addWidget(self.audioDataPath, 0, 2, 1, 1)
        self.serviceAccountPath = QtWidgets.QLineEdit(self.groupBox)
        self.serviceAccountPath.setObjectName("serviceAccountPath")
        self.gridLayout_2.addWidget(self.serviceAccountPath, 1, 2, 1, 1)
        self.btnImportAudio = QtWidgets.QPushButton(self.groupBox)
        self.btnImportAudio.setObjectName("btnImportAudio")
        self.gridLayout_2.addWidget(self.btnImportAudio, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.btnImportServiceAccount = QtWidgets.QPushButton(self.groupBox)
        self.btnImportServiceAccount.setObjectName("btnImportServiceAccount")
        self.gridLayout_2.addWidget(self.btnImportServiceAccount, 1, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 2)

        self.retranslateUi(SpeechToText)
        QtCore.QMetaObject.connectSlotsByName(SpeechToText)

    def retranslateUi(self, SpeechToText):
        _translate = QtCore.QCoreApplication.translate
        self.btnTranscribe.setText(_translate("SpeechToText", "Transcribe"))
        self.groupBox_2.setTitle(_translate("SpeechToText", "Parameters"))
        self.label_2.setText(_translate("SpeechToText", "Sample Rate (Hz)"))
        self.label_8.setText(_translate("SpeechToText", "Encoding"))
        self.label_7.setText(_translate("SpeechToText", "Use Enhanced"))
        self.label_5.setText(_translate("SpeechToText", "Model"))
        self.label_4.setText(_translate("SpeechToText", "Language"))
        self.groupBox_3.setTitle(_translate("SpeechToText", "Result"))
        self.transcriptionResult.setHtml(_translate("SpeechToText", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.groupBox.setTitle(_translate("SpeechToText", "Input Files"))
        self.label.setText(_translate("SpeechToText", "Audio Data"))
        self.btnImportAudio.setText(_translate("SpeechToText", "Import"))
        self.label_3.setText(_translate("SpeechToText", "Google Service Account"))
        self.btnImportServiceAccount.setText(_translate("SpeechToText", "Import"))

